package setup

import (
	"fmt"
	"os"
	"os/user"
	"path/filepath"
	"strings"
)

// ConfigureShell sets up a comfortable zsh environment for each named user.
// It registers the Homebrew-managed zsh in /etc/shells (once), then per user:
// switches the default shell to brew zsh and writes a .zshrc with autosuggestions,
// syntax highlighting, and useful server-admin aliases.
//
// The same user list used for SSH key installation is passed in (root, $SUDO_USER,
// --username) so every SSH-capable account gets an identical shell environment.
//
// .zshrc is only written when the file does not already exist, preserving any
// customisation the user has already made.
func ConfigureShell(r *Runner, users []string) []Result {
	if len(users) == 0 {
		return []Result{SkipResult("shell", "no users specified")}
	}

	var results []Result

	brewZsh := BrewPrefix() + "/bin/zsh"

	// Register brew zsh in /etc/shells once, regardless of how many users
	// are being configured. This is required before chsh will accept it.
	results = append(results, ensureZshInShells(r, brewZsh))

	for _, name := range users {
		results = append(results, switchShell(r, name, brewZsh)...)
	}

	return results
}

// ensureZshInShells appends the brew zsh path to /etc/shells when it is not
// already listed. Without this entry, chsh rejects the shell change.
func ensureZshInShells(r *Runner, brewZsh string) Result {
	data, err := os.ReadFile("/etc/shells")
	if err != nil {
		return FailResult("shell-etc-shells", "failed to read /etc/shells", err)
	}

	for line := range strings.SplitSeq(string(data), "\n") {
		if strings.TrimSpace(line) == brewZsh {
			return SkipResult("shell-etc-shells", brewZsh+" already in /etc/shells")
		}
	}

	if r.DryRun {
		fmt.Printf("  [dry-run] echo %s >> /etc/shells\n", brewZsh)
		return OKResult("shell-etc-shells", "would register "+brewZsh+" in /etc/shells (dry-run)")
	}

	f, err := os.OpenFile("/etc/shells", os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		return FailResult("shell-etc-shells", "failed to open /etc/shells for writing", err)
	}
	defer f.Close()

	if _, err := fmt.Fprintln(f, brewZsh); err != nil {
		return FailResult("shell-etc-shells", "failed to write to /etc/shells", err)
	}

	return OKResult("shell-etc-shells", "registered "+brewZsh+" in /etc/shells")
}

// switchShell sets the default shell for a single user and writes their .zshrc.
func switchShell(r *Runner, name, brewZsh string) []Result {
	step := "shell[" + name + "]"
	var results []Result

	u, err := user.Lookup(name)
	if err != nil {
		return []Result{FailResult(step, fmt.Sprintf("user %q not found", name), err)}
	}

	// Change the default shell only when it differs from the brew zsh path.
	// dscl output is "UserShell: /path/to/zsh" — we extract the path portion.
	out, _ := r.Read("dscl", ".", "-read", "/Users/"+name, "UserShell")
	currentShell := strings.TrimSpace(strings.TrimPrefix(out, "UserShell:"))
	if strings.TrimSpace(currentShell) == brewZsh {
		results = append(results, SkipResult(step+"-chsh",
			fmt.Sprintf("%s already uses brew zsh", name)))
	} else {
		out, err := r.Run("chsh", "-s", brewZsh, name)
		if err != nil {
			results = append(results, FailResult(step+"-chsh",
				fmt.Sprintf("chsh for %s: %s", name, out), err))
			// Continue — we can still write the .zshrc even if chsh failed.
		} else {
			results = append(results, OKResult(step+"-chsh",
				fmt.Sprintf("default shell for %s set to brew zsh", name)))
		}
	}

	results = append(results, writeZshrc(r, name, u.HomeDir))
	return results
}

// writeZshrc writes a .zshrc for the given user. It skips the write when the
// file already exists so that existing customisations are not overwritten.
func writeZshrc(r *Runner, name, homeDir string) Result {
	step := "shell[" + name + "]-zshrc"
	zshrcPath := filepath.Join(homeDir, ".zshrc")

	if _, err := os.Stat(zshrcPath); err == nil {
		return SkipResult(step, zshrcPath+" already exists")
	}

	prefix := BrewPrefix()
	content := fmt.Sprintf(`# Generated by setupmac — edit freely, this file will not be overwritten.
eval "$(%s/bin/brew shellenv)"
export EDITOR=vim
export LANG=en_US.UTF-8

# Zsh plugins (installed via brew)
source %s/share/zsh-autosuggestions/zsh-autosuggestions.zsh
export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=%s/share/zsh-syntax-highlighting/highlighters
source %s/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Aliases
alias ll='ls -la'
alias la='ls -A'
alias ..='cd ..'
alias ...='cd ../..'
alias ports='lsof -i -P -n | grep LISTEN'
`, prefix, prefix, prefix, prefix)

	if r.DryRun {
		fmt.Printf("  [dry-run] write %s\n", zshrcPath)
		return OKResult(step, fmt.Sprintf("would write %s (dry-run)", zshrcPath))
	}

	if err := os.WriteFile(zshrcPath, []byte(content), 0644); err != nil {
		return FailResult(step, fmt.Sprintf("failed to write %s: %v", zshrcPath, err), err)
	}

	// Set ownership to the user so they can edit the file without sudo.
	if err := chownPath(zshrcPath, name, "staff"); err != nil {
		return FailResult(step,
			fmt.Sprintf("failed to set ownership of %s: %v", zshrcPath, err), err)
	}

	return OKResult(step, fmt.Sprintf("wrote %s", zshrcPath))
}
